services:
  - type: web
    name: server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://kigenbrandon:jzhIc5fLgY15J9Q6@cluster0.fazs7lj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: your_jwt_secret
    autoDeploy: true
    rootDir: server

  - type: web
    name: client
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: serve -s dist
    envVars:
      - key: VITE_API_URL
        value: https://week-6-test-debug-assignment-kigenbrandon.onrender.com
    autoDeploy: true
    rootDir: client
